version: '3.7'

services:
  radicale:
    container_name: radicale
    image: radicale:3.1.1-1
    ports:
      - "127.0.0.1:5232:5232"
    #init: true
    read_only: true
    user: "3999"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 120s
      retries: 3
    volumes:
      - data:/var/lib/radicale
      - config:/etc/radicale:ro
#      - /var/log/radicale:/var/log/radicale
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
#      - USER_UID=3999
#      - USER_GID=3999
    restart: unless-stopped

volumes:
  config:
    external:
      name: radicale-config
  data:
    external:
      name: radicale-data
